services:
  frontend:
    build: ./client
    container_name: frontend
    depends_on:
      - gateway
    ports:
      - "8088:80"
  gateway:
    build: ./gateway
    container_name: gateway
    depends_on:
      - user
      - product
      - order
    environment:
      SERVER_PORT: 8080
      PRODUCT_SERVICE_URL: http://product:8082
      USER_SERVICE_URL: http://user:8081
      ORDER_SERVICE_URL: http://order:8083
    ports:
      - "4015:8080"
  user:
    build: ./user-service
    container_name: user
    depends_on: 
      - users_db
    environment:
      SERVER_PORT: 8081
      SPRING_DATASOURCE_URL: jdbc:postgresql://users_db:5432/users_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123
    ports:
      - "8081:8081"
  product:
    build: ./product-service
    container_name: product
    depends_on: 
      - products_db
    environment:
      SERVER_PORT: 8082
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123
      SPRING_DATASOURCE_URL: jdbc:postgresql://products_db:5432/products_db
    ports:
      - "8082:8082"
  order:
    build: ./order-service
    container_name: order
    depends_on:
      - user
      - product
      - orders_db
    environment:
      SERVER_PORT: 8083
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres123
      SPRING_DATASOURCE_URL: jdbc:postgresql://orders_db:5432/orders_db
    ports:
      - "8083:8083"
  
  users_db:
    image: postgres:16
    container_name: users_db
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - user_db_data:/var/lib/postgresql/data

  products_db:
    image: postgres:16
    container_name: products_db
    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - product_db_data:/var/lib/postgresql/data

  orders_db:
    image: postgres:16
    container_name: orders_db
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
    volumes:
      - order_db_data:/var/lib/postgresql/data

volumes:
  user_db_data: 
  product_db_data: 
  order_db_data:
